import { initializeApp } from "firebase/app";
import { getFirestore, collection, setDoc, doc } from "firebase/firestore";
import { db } from "../firebase-config.js"; // Adjust the import path as necessary

const powerSupplyData = [
  {
    id: "psu001",
    title: "Sample Power Supply Model 1",
    name: "Corsair RM750x",
    type: "ATX",
    efficiency: "80+ Gold",
    wattage: "750W",
    modular: "Yes",
    rating: 4.6,
    price: 119,
    description: "Sample description for power supply model 1. High-quality 750W modular power supply with 80+ Gold efficiency and excellent reliability.",
    imageUrl: "https://example.com/psu1.jpg",
  },
  {
    id: "psu002",
    title: "Sample Power Supply Model 2",
    name: "EVGA SuperNOVA 650 G5",
    type: "ATX",
    efficiency: "80+ Gold",
    wattage: "650W",
    modular: "Yes",
    rating: 4.4,
    price: 99,
    description: "Sample description for power supply model 2. Reliable 650W fully modular power supply with 80+ Gold efficiency and 10-year warranty.",
    imageUrl: "https://example.com/psu2.jpg",
  },
  {
    id: "psu003",
    title: "Sample Power Supply Model 3",
    name: "Seasonic Focus GX-550",
    type: "ATX",
    efficiency: "80+ Gold",
    wattage: "550W",
    modular: "Yes",
    rating: 4.5,
    price: 89,
    description: "Sample description for power supply model 3. Premium 550W modular power supply with 80+ Gold efficiency and excellent build quality.",
    imageUrl: "https://example.com/psu3.jpg",
  },
  {
    id: "psu004",
    title: "Sample Power Supply Model 4",
    name: "be quiet! Straight Power 11 850W",
    type: "ATX",
    efficiency: "80+ Gold",
    wattage: "850W",
    modular: "Yes",
    rating: 4.7,
    price: 149,
    description: "Sample description for power supply model 4. Silent 850W modular power supply with 80+ Gold efficiency and excellent noise performance.",
    imageUrl: "https://example.com/psu4.jpg",
  },
  {
    id: "psu005",
    title: "Sample Power Supply Model 5",
    name: "Cooler Master MWE Gold 750",
    type: "ATX",
    efficiency: "80+ Gold",
    wattage: "750W",
    modular: "Semi",
    rating: 4.2,
    price: 89,
    description: "Sample description for power supply model 5. Affordable 750W semi-modular power supply with 80+ Gold efficiency and good performance.",
    imageUrl: "https://example.com/psu5.jpg",
  },
  {
    id: "psu006",
    title: "Sample Power Supply Model 6",
    name: "Corsair HX1000",
    type: "ATX",
    efficiency: "80+ Platinum",
    wattage: "1000W",
    modular: "Yes",
    rating: 4.8,
    price: 199,
    description: "Sample description for power supply model 6. Premium 1000W fully modular power supply with 80+ Platinum efficiency for high-end builds.",
    imageUrl: "https://example.com/psu6.jpg",
  },
  {
    id: "psu007",
    title: "Sample Power Supply Model 7",
    name: "EVGA 600 BR",
    type: "ATX",
    efficiency: "80+ Bronze",
    wattage: "600W",
    modular: "No",
    rating: 3.9,
    price: 49,
    description: "Sample description for power supply model 7. Budget 600W non-modular power supply with 80+ Bronze efficiency for basic builds.",
    imageUrl: "https://example.com/psu7.jpg",
  },
  {
    id: "psu008",
    title: "Sample Power Supply Model 8",
    name: "Seasonic PRIME TX-1300",
    type: "ATX",
    efficiency: "80+ Titanium",
    wattage: "1300W",
    modular: "Yes",
    rating: 4.9,
    price: 399,
    description: "Sample description for power supply model 8. Ultimate 1300W fully modular power supply with 80+ Titanium efficiency for extreme builds.",
    imageUrl: "https://example.com/psu8.jpg",
  },
  {
    id: "psu009",
    title: "Sample Power Supply Model 9",
    name: "be quiet! Pure Power 11 600W",
    type: "ATX",
    efficiency: "80+ Gold",
    wattage: "600W",
    modular: "Semi",
    rating: 4.3,
    price: 79,
    description: "Sample description for power supply model 9. Silent 600W semi-modular power supply with 80+ Gold efficiency and excellent noise levels.",
    imageUrl: "https://example.com/psu9.jpg",
  },
  {
    id: "psu010",
    title: "Sample Power Supply Model 10",
    name: "Corsair SF750",
    type: "SFX",
    efficiency: "80+ Platinum",
    wattage: "750W",
    modular: "Yes",
    rating: 4.7,
    price: 179,
    description: "Sample description for power supply model 10. Compact 750W SFX modular power supply with 80+ Platinum efficiency for small form factor builds.",
    imageUrl: "https://example.com/psu10.jpg",
  },
  {
    id: "psu011",
    title: "Sample Power Supply Model 11",
    name: "EVGA SuperNOVA 850 G6",
    type: "ATX",
    efficiency: "80+ Gold",
    wattage: "850W",
    modular: "Yes",
    rating: 4.5,
    price: 129,
    description: "Sample description for power supply model 11. High-performance 850W fully modular power supply with 80+ Gold efficiency and excellent reliability.",
    imageUrl: "https://example.com/psu11.jpg",
  },
  {
    id: "psu012",
    title: "Sample Power Supply Model 12",
    name: "Seasonic Focus SGX-650",
    type: "SFX-L",
    efficiency: "80+ Gold",
    wattage: "650W",
    modular: "Yes",
    rating: 4.4,
    price: 119,
    description: "Sample description for power supply model 12. Compact 650W SFX-L modular power supply with 80+ Gold efficiency for mini-ITX builds.",
    imageUrl: "https://example.com/psu12.jpg",
  },
  {
    id: "psu013",
    title: "Sample Power Supply Model 13",
    name: "Cooler Master V850 SFX",
    type: "SFX",
    efficiency: "80+ Gold",
    wattage: "850W",
    modular: "Yes",
    rating: 4.6,
    price: 149,
    description: "Sample description for power supply model 13. High-wattage 850W SFX modular power supply with 80+ Gold efficiency for powerful small builds.",
    imageUrl: "https://example.com/psu13.jpg",
  },
  {
    id: "psu014",
    title: "Sample Power Supply Model 14",
    name: "be quiet! Dark Power Pro 12 1200W",
    type: "ATX",
    efficiency: "80+ Titanium",
    wattage: "1200W",
    modular: "Yes",
    rating: 4.8,
    price: 299,
    description: "Sample description for power supply model 14. Premium 1200W fully modular power supply with 80+ Titanium efficiency and exceptional build quality.",
    imageUrl: "https://example.com/psu14.jpg",
  },
  {
    id: "psu015",
    title: "Sample Power Supply Model 15",
    name: "Corsair CX650F",
    type: "ATX",
    efficiency: "80+ Bronze",
    wattage: "650W",
    modular: "Semi",
    rating: 4.1,
    price: 69,
    description: "Sample description for power supply model 15. Affordable 650W semi-modular power supply with 80+ Bronze efficiency and RGB lighting.",
    imageUrl: "https://example.com/psu15.jpg",
  },
  {
    id: "psu016",
    title: "Sample Power Supply Model 16",
    name: "EVGA 500 BQ",
    type: "ATX",
    efficiency: "80+ Bronze",
    wattage: "500W",
    modular: "Semi",
    rating: 4.0,
    price: 59,
    description: "Sample description for power supply model 16. Budget 500W semi-modular power supply with 80+ Bronze efficiency for entry-level builds.",
    imageUrl: "https://example.com/psu16.jpg",
  },
  {
    id: "psu017",
    title: "Sample Power Supply Model 17",
    name: "Seasonic S12III 500",
    type: "ATX",
    efficiency: "80+ Bronze",
    wattage: "500W",
    modular: "No",
    rating: 3.8,
    price: 49,
    description: "Sample description for power supply model 17. Reliable 500W non-modular power supply with 80+ Bronze efficiency for basic systems.",
    imageUrl: "https://example.com/psu17.jpg",
  },
  {
    id: "psu018",
    title: "Sample Power Supply Model 18",
    name: "Corsair AX1600i",
    type: "ATX",
    efficiency: "80+ Titanium",
    wattage: "1600W",
    modular: "Yes",
    rating: 4.9,
    price: 499,
    description: "Sample description for power supply model 18. Ultimate 1600W fully modular power supply with 80+ Titanium efficiency for extreme multi-GPU setups.",
    imageUrl: "https://example.com/psu18.jpg",
  },
  {
    id: "psu019",
    title: "Sample Power Supply Model 19",
    name: "be quiet! System Power 9 400W",
    type: "ATX",
    efficiency: "80+ Bronze",
    wattage: "400W",
    modular: "No",
    rating: 3.9,
    price: 39,
    description: "Sample description for power supply model 19. Compact 400W non-modular power supply with 80+ Bronze efficiency for basic office builds.",
    imageUrl: "https://example.com/psu19.jpg",
  },
  {
    id: "psu020",
    title: "Sample Power Supply Model 20",
    name: "EVGA SuperNOVA 1000 P2",
    type: "ATX",
    efficiency: "80+ Platinum",
    wattage: "1000W",
    modular: "Yes",
    rating: 4.7,
    price: 189,
    description: "Sample description for power supply model 20. High-performance 1000W fully modular power supply with 80+ Platinum efficiency and 10-year warranty.",
    imageUrl: "https://example.com/psu20.jpg",
  },
  {
    id: "psu021",
    title: "Sample Power Supply Model 21",
    name: "Seasonic Focus GX-850",
    type: "ATX",
    efficiency: "80+ Gold",
    wattage: "850W",
    modular: "Yes",
    rating: 4.6,
    price: 129,
    description: "Sample description for power supply model 21. Premium 850W fully modular power supply with 80+ Gold efficiency and excellent reliability.",
    imageUrl: "https://example.com/psu21.jpg",
  },
  {
    id: "psu022",
    title: "Sample Power Supply Model 22",
    name: "Cooler Master MWE Bronze 450",
    type: "ATX",
    efficiency: "80+ Bronze",
    wattage: "450W",
    modular: "No",
    rating: 3.8,
    price: 44,
    description: "Sample description for power supply model 22. Budget 450W non-modular power supply with 80+ Bronze efficiency for basic gaming builds.",
    imageUrl: "https://example.com/psu22.jpg",
  },
  {
    id: "psu023",
    title: "Sample Power Supply Model 23",
    name: "Corsair RM850x",
    type: "ATX",
    efficiency: "80+ Gold",
    wattage: "850W",
    modular: "Yes",
    rating: 4.5,
    price: 139,
    description: "Sample description for power supply model 23. Reliable 850W fully modular power supply with 80+ Gold efficiency and excellent performance.",
    imageUrl: "https://example.com/psu23.jpg",
  },
  {
    id: "psu024",
    title: "Sample Power Supply Model 24",
    name: "be quiet! Straight Power 11 550W",
    type: "ATX",
    efficiency: "80+ Gold",
    wattage: "550W",
    modular: "Yes",
    rating: 4.4,
    price: 99,
    description: "Sample description for power supply model 24. Silent 550W fully modular power supply with 80+ Gold efficiency and excellent noise performance.",
    imageUrl: "https://example.com/psu24.jpg",
  },
  {
    id: "psu025",
    title: "Sample Power Supply Model 25",
    name: "EVGA 750 BQ",
    type: "ATX",
    efficiency: "80+ Bronze",
    wattage: "750W",
    modular: "Semi",
    rating: 4.1,
    price: 79,
    description: "Sample description for power supply model 25. Affordable 750W semi-modular power supply with 80+ Bronze efficiency for mid-range builds.",
    imageUrl: "https://example.com/psu25.jpg",
  },
  {
    id: "psu026",
    title: "Sample Power Supply Model 26",
    name: "Seasonic PRIME GX-1000",
    type: "ATX",
    efficiency: "80+ Gold",
    wattage: "1000W",
    modular: "Yes",
    rating: 4.7,
    price: 179,
    description: "Sample description for power supply model 26. Premium 1000W fully modular power supply with 80+ Gold efficiency and 12-year warranty.",
    imageUrl: "https://example.com/psu26.jpg",
  },
  {
    id: "psu027",
    title: "Sample Power Supply Model 27",
    name: "Corsair SF600",
    type: "SFX",
    efficiency: "80+ Gold",
    wattage: "600W",
    modular: "Yes",
    rating: 4.6,
    price: 119,
    description: "Sample description for power supply model 27. Compact 600W SFX modular power supply with 80+ Gold efficiency for small form factor builds.",
    imageUrl: "https://example.com/psu27.jpg",
  },
  {
    id: "psu028",
    title: "Sample Power Supply Model 28",
    name: "be quiet! Dark Power Pro 12 850W",
    type: "ATX",
    efficiency: "80+ Titanium",
    wattage: "850W",
    modular: "Yes",
    rating: 4.8,
    price: 249,
    description: "Sample description for power supply model 28. Premium 850W fully modular power supply with 80+ Titanium efficiency and exceptional build quality.",
    imageUrl: "https://example.com/psu28.jpg",
  },
  {
    id: "psu029",
    title: "Sample Power Supply Model 29",
    name: "EVGA SuperNOVA 550 G3",
    type: "ATX",
    efficiency: "80+ Gold",
    wattage: "550W",
    modular: "Yes",
    rating: 4.3,
    price: 89,
    description: "Sample description for power supply model 29. Compact 550W fully modular power supply with 80+ Gold efficiency and excellent reliability.",
    imageUrl: "https://example.com/psu29.jpg",
  },
  {
    id: "psu030",
    title: "Sample Power Supply Model 30",
    name: "Seasonic Focus GX-1000",
    type: "ATX",
    efficiency: "80+ Gold",
    wattage: "1000W",
    modular: "Yes",
    rating: 4.6,
    price: 159,
    description: "Sample description for power supply model 30. High-performance 1000W fully modular power supply with 80+ Gold efficiency and excellent build quality.",
    imageUrl: "https://example.com/psu30.jpg",
  },
];

// async function uploadPowerSupplyData() {
//   const sparePartsRef = collection(db, "SparePart");

//   for (let psu of powerSupplyData) {
//     try {
//       await setDoc(doc(sparePartsRef, psu.id), psu);
//       console.log(`✅ Uploaded: ${psu.title}`);
//     } catch (err) {
//       console.error(`❌ Failed to upload ${psu.title}:`, err);
//     }
//   }

//   console.log("🎉 All Power Supply data uploaded!");
// }

// uploadPowerSupplyData();

for (let psu of powerSupplyData) {
  try {
    await setDoc(doc(db, "powerSupplyData", psu.id), psu);
    console.log(`✅ Uploaded: ${psu.title}`);
  } catch (err) {
    console.error(`❌ Failed to upload ${psu.title}:`, err);
  }
}
