import { initializeApp } from "firebase/app";
import { getFirestore, collection, setDoc, doc } from "firebase/firestore";
import { db } from "../firebase-config.js"; // Adjust the import path as necessary

const mainboardData = [
  {
    id: "mainboard001",
    title: "Sample Mainboard Model 1",
    name: "ASUS ROG STRIX B550-F GAMING",
    cpuSocket: "AM4",
    memoryMax: "128GB",
    formFactor: "ATX",
    memorySlots: 4,
    rating: 4.5,
    price: 179,
    description: "Sample description for mainboard model 1. High-performance AMD B550 motherboard with excellent gaming features and RGB lighting.",
    imageUrl: "https://example.com/mainboard1.jpg",
  },
  {
    id: "mainboard002",
    title: "Sample Mainboard Model 2",
    name: "MSI MPG B550 GAMING EDGE WIFI",
    cpuSocket: "AM4",
    memoryMax: "128GB",
    formFactor: "ATX",
    memorySlots: 4,
    rating: 4.3,
    price: 189,
    description: "Sample description for mainboard model 2. Feature-rich B550 motherboard with built-in WiFi and premium audio.",
    imageUrl: "https://example.com/mainboard2.jpg",
  },
  {
    id: "mainboard003",
    title: "Sample Mainboard Model 3",
    name: "Gigabyte B550 AORUS PRO AC",
    cpuSocket: "AM4",
    memoryMax: "128GB",
    formFactor: "ATX",
    memorySlots: 4,
    rating: 4.4,
    price: 169,
    description: "Sample description for mainboard model 3. Reliable B550 motherboard with excellent VRM design and networking features.",
    imageUrl: "https://example.com/mainboard3.jpg",
  },
  {
    id: "mainboard004",
    title: "Sample Mainboard Model 4",
    name: "ASRock B550M Steel Legend",
    cpuSocket: "AM4",
    memoryMax: "128GB",
    formFactor: "Micro-ATX",
    memorySlots: 4,
    rating: 4.1,
    price: 119,
    description: "Sample description for mainboard model 4. Compact micro-ATX B550 motherboard with steel armor and good performance.",
    imageUrl: "https://example.com/mainboard4.jpg",
  },
  {
    id: "mainboard005",
    title: "Sample Mainboard Model 5",
    name: "ASUS TUF GAMING B550M-PLUS",
    cpuSocket: "AM4",
    memoryMax: "128GB",
    formFactor: "Micro-ATX",
    memorySlots: 4,
    rating: 4.2,
    price: 109,
    description: "Sample description for mainboard model 5. Military-grade micro-ATX B550 motherboard with excellent durability.",
    imageUrl: "https://example.com/mainboard5.jpg",
  },
  {
    id: "mainboard006",
    title: "Sample Mainboard Model 6",
    name: "MSI B550M PRO-VDH WIFI",
    cpuSocket: "AM4",
    memoryMax: "128GB",
    formFactor: "Micro-ATX",
    memorySlots: 4,
    rating: 4.0,
    price: 99,
    description: "Sample description for mainboard model 6. Budget-friendly micro-ATX B550 motherboard with WiFi connectivity.",
    imageUrl: "https://example.com/mainboard6.jpg",
  },
  {
    id: "mainboard007",
    title: "Sample Mainboard Model 7",
    name: "ASUS ROG STRIX X570-E GAMING",
    cpuSocket: "AM4",
    memoryMax: "128GB",
    formFactor: "ATX",
    memorySlots: 4,
    rating: 4.7,
    price: 299,
    description: "Sample description for mainboard model 7. Premium X570 motherboard with PCIe 4.0 support and advanced features.",
    imageUrl: "https://example.com/mainboard7.jpg",
  },
  {
    id: "mainboard008",
    title: "Sample Mainboard Model 8",
    name: "MSI MEG X570 ACE",
    cpuSocket: "AM4",
    memoryMax: "128GB",
    formFactor: "ATX",
    memorySlots: 4,
    rating: 4.6,
    price: 349,
    description: "Sample description for mainboard model 8. High-end X570 motherboard with premium components and excellent overclocking.",
    imageUrl: "https://example.com/mainboard8.jpg",
  },
  {
    id: "mainboard009",
    title: "Sample Mainboard Model 9",
    name: "Gigabyte X570 AORUS MASTER",
    cpuSocket: "AM4",
    memoryMax: "128GB",
    formFactor: "ATX",
    memorySlots: 4,
    rating: 4.5,
    price: 329,
    description: "Sample description for mainboard model 9. Flagship X570 motherboard with advanced cooling and premium features.",
    imageUrl: "https://example.com/mainboard9.jpg",
  },
  {
    id: "mainboard010",
    title: "Sample Mainboard Model 10",
    name: "ASRock X570 Taichi",
    cpuSocket: "AM4",
    memoryMax: "128GB",
    formFactor: "ATX",
    memorySlots: 4,
    rating: 4.4,
    price: 289,
    description: "Sample description for mainboard model 10. Premium X570 motherboard with unique design and excellent performance.",
    imageUrl: "https://example.com/mainboard10.jpg",
  },
  {
    id: "mainboard011",
    title: "Sample Mainboard Model 11",
    name: "ASUS ROG STRIX Z690-E GAMING WIFI",
    cpuSocket: "LGA1700",
    memoryMax: "128GB",
    formFactor: "ATX",
    memorySlots: 4,
    rating: 4.6,
    price: 399,
    description: "Sample description for mainboard model 11. High-performance Intel Z690 motherboard with DDR5 support and WiFi 6E.",
    imageUrl: "https://example.com/mainboard11.jpg",
  },
  {
    id: "mainboard012",
    title: "Sample Mainboard Model 12",
    name: "MSI MPG Z690 GAMING EDGE WIFI",
    cpuSocket: "LGA1700",
    memoryMax: "128GB",
    formFactor: "ATX",
    memorySlots: 4,
    rating: 4.4,
    price: 379,
    description: "Sample description for mainboard model 12. Feature-rich Z690 motherboard with DDR5 support and premium audio.",
    imageUrl: "https://example.com/mainboard12.jpg",
  },
  {
    id: "mainboard013",
    title: "Sample Mainboard Model 13",
    name: "Gigabyte Z690 AORUS ELITE AX",
    cpuSocket: "LGA1700",
    memoryMax: "128GB",
    formFactor: "ATX",
    memorySlots: 4,
    rating: 4.3,
    price: 359,
    description: "Sample description for mainboard model 13. Reliable Z690 motherboard with DDR5 support and excellent VRM design.",
    imageUrl: "https://example.com/mainboard13.jpg",
  },
  {
    id: "mainboard014",
    title: "Sample Mainboard Model 14",
    name: "ASRock Z690 Steel Legend",
    cpuSocket: "LGA1700",
    memoryMax: "128GB",
    formFactor: "ATX",
    memorySlots: 4,
    rating: 4.2,
    price: 239,
    description: "Sample description for mainboard model 14. Affordable Z690 motherboard with DDR5 support and steel armor design.",
    imageUrl: "https://example.com/mainboard14.jpg",
  },
  {
    id: "mainboard015",
    title: "Sample Mainboard Model 15",
    name: "ASUS TUF GAMING Z690-PLUS WIFI",
    cpuSocket: "LGA1700",
    memoryMax: "128GB",
    formFactor: "ATX",
    memorySlots: 4,
    rating: 4.1,
    price: 229,
    description: "Sample description for mainboard model 15. Military-grade Z690 motherboard with DDR5 support and WiFi connectivity.",
    imageUrl: "https://example.com/mainboard15.jpg",
  },
  {
    id: "mainboard016",
    title: "Sample Mainboard Model 16",
    name: "MSI PRO Z690-A WIFI",
    cpuSocket: "LGA1700",
    memoryMax: "128GB",
    formFactor: "ATX",
    memorySlots: 4,
    rating: 4.0,
    price: 199,
    description: "Sample description for mainboard model 16. Budget-friendly Z690 motherboard with DDR5 support and WiFi.",
    imageUrl: "https://example.com/mainboard16.jpg",
  },
  {
    id: "mainboard017",
    title: "Sample Mainboard Model 17",
    name: "Gigabyte B660M AORUS PRO AX",
    cpuSocket: "LGA1700",
    memoryMax: "128GB",
    formFactor: "Micro-ATX",
    memorySlots: 4,
    rating: 4.2,
    price: 149,
    description: "Sample description for mainboard model 17. Compact micro-ATX B660 motherboard with DDR5 support and WiFi.",
    imageUrl: "https://example.com/mainboard17.jpg",
  },
  {
    id: "mainboard018",
    title: "Sample Mainboard Model 18",
    name: "ASUS PRIME B660M-A WIFI",
    cpuSocket: "LGA1700",
    memoryMax: "128GB",
    formFactor: "Micro-ATX",
    memorySlots: 4,
    rating: 4.0,
    price: 129,
    description: "Sample description for mainboard model 18. Reliable micro-ATX B660 motherboard with DDR5 support and WiFi.",
    imageUrl: "https://example.com/mainboard18.jpg",
  },
  {
    id: "mainboard019",
    title: "Sample Mainboard Model 19",
    name: "MSI B660M MORTAR WIFI",
    cpuSocket: "LGA1700",
    memoryMax: "128GB",
    formFactor: "Micro-ATX",
    memorySlots: 4,
    rating: 4.1,
    price: 139,
    description: "Sample description for mainboard model 19. Gaming-focused micro-ATX B660 motherboard with DDR5 support.",
    imageUrl: "https://example.com/mainboard19.jpg",
  },
  {
    id: "mainboard020",
    title: "Sample Mainboard Model 20",
    name: "ASRock B660M-ITX/ac",
    cpuSocket: "LGA1700",
    memoryMax: "64GB",
    formFactor: "Mini-ITX",
    memorySlots: 2,
    rating: 4.3,
    price: 119,
    description: "Sample description for mainboard model 20. Compact mini-ITX B660 motherboard with WiFi for small form factor builds.",
    imageUrl: "https://example.com/mainboard20.jpg",
  },
  {
    id: "mainboard021",
    title: "Sample Mainboard Model 21",
    name: "ASUS ROG STRIX B660-I GAMING WIFI",
    cpuSocket: "LGA1700",
    memoryMax: "64GB",
    formFactor: "Mini-ITX",
    memorySlots: 2,
    rating: 4.4,
    price: 189,
    description: "Sample description for mainboard model 21. Premium mini-ITX B660 motherboard with DDR5 support and gaming features.",
    imageUrl: "https://example.com/mainboard21.jpg",
  },
  {
    id: "mainboard022",
    title: "Sample Mainboard Model 22",
    name: "MSI MPG B660I EDGE WIFI",
    cpuSocket: "LGA1700",
    memoryMax: "64GB",
    formFactor: "Mini-ITX",
    memorySlots: 2,
    rating: 4.2,
    price: 169,
    description: "Sample description for mainboard model 22. Feature-rich mini-ITX B660 motherboard with DDR5 support and WiFi.",
    imageUrl: "https://example.com/mainboard22.jpg",
  },
  {
    id: "mainboard023",
    title: "Sample Mainboard Model 23",
    name: "Gigabyte B660I AORUS PRO DDR4",
    cpuSocket: "LGA1700",
    memoryMax: "64GB",
    formFactor: "Mini-ITX",
    memorySlots: 2,
    rating: 4.1,
    price: 149,
    description: "Sample description for mainboard model 23. Compact mini-ITX B660 motherboard with DDR4 support for budget builds.",
    imageUrl: "https://example.com/mainboard23.jpg",
  },
  {
    id: "mainboard024",
    title: "Sample Mainboard Model 24",
    name: "ASRock B550M-ITX/ac",
    cpuSocket: "AM4",
    memoryMax: "64GB",
    formFactor: "Mini-ITX",
    memorySlots: 2,
    rating: 4.0,
    price: 109,
    description: "Sample description for mainboard model 24. Affordable mini-ITX B550 motherboard with WiFi for small builds.",
    imageUrl: "https://example.com/mainboard24.jpg",
  },
  {
    id: "mainboard025",
    title: "Sample Mainboard Model 25",
    name: "ASUS ROG STRIX B550-I GAMING",
    cpuSocket: "AM4",
    memoryMax: "64GB",
    formFactor: "Mini-ITX",
    memorySlots: 2,
    rating: 4.3,
    price: 179,
    description: "Sample description for mainboard model 25. Premium mini-ITX B550 motherboard with gaming features and RGB lighting.",
    imageUrl: "https://example.com/mainboard25.jpg",
  },
  {
    id: "mainboard026",
    title: "Sample Mainboard Model 26",
    name: "MSI MPG B550I GAMING EDGE WIFI",
    cpuSocket: "AM4",
    memoryMax: "64GB",
    formFactor: "Mini-ITX",
    memorySlots: 2,
    rating: 4.2,
    price: 159,
    description: "Sample description for mainboard model 26. Gaming-focused mini-ITX B550 motherboard with WiFi and premium audio.",
    imageUrl: "https://example.com/mainboard26.jpg",
  },
  {
    id: "mainboard027",
    title: "Sample Mainboard Model 27",
    name: "Gigabyte B550I AORUS PRO AX",
    cpuSocket: "AM4",
    memoryMax: "64GB",
    formFactor: "Mini-ITX",
    memorySlots: 2,
    rating: 4.1,
    price: 139,
    description: "Sample description for mainboard model 27. Reliable mini-ITX B550 motherboard with WiFi and good VRM design.",
    imageUrl: "https://example.com/mainboard27.jpg",
  },
  {
    id: "mainboard028",
    title: "Sample Mainboard Model 28",
    name: "ASRock X570M Pro4",
    cpuSocket: "AM4",
    memoryMax: "128GB",
    formFactor: "Micro-ATX",
    memorySlots: 4,
    rating: 4.0,
    price: 159,
    description: "Sample description for mainboard model 28. Compact micro-ATX X570 motherboard with PCIe 4.0 support.",
    imageUrl: "https://example.com/mainboard28.jpg",
  },
  {
    id: "mainboard029",
    title: "Sample Mainboard Model 29",
    name: "ASUS TUF GAMING X570-PRO",
    cpuSocket: "AM4",
    memoryMax: "128GB",
    formFactor: "ATX",
    memorySlots: 4,
    rating: 4.3,
    price: 229,
    description: "Sample description for mainboard model 29. Military-grade X570 motherboard with PCIe 4.0 and excellent durability.",
    imageUrl: "https://example.com/mainboard29.jpg",
  },
  {
    id: "mainboard030",
    title: "Sample Mainboard Model 30",
    name: "MSI MEG Z690I UNIFY",
    cpuSocket: "LGA1700",
    memoryMax: "64GB",
    formFactor: "Mini-ITX",
    memorySlots: 2,
    rating: 4.7,
    price: 399,
    description: "Sample description for mainboard model 30. Premium mini-ITX Z690 motherboard with DDR5 support and extreme overclocking features.",
    imageUrl: "https://example.com/mainboard30.jpg",
  },
];

// async function uploadMainboardData() {
//   const sparePartsRef = collection(db, "SparePart");

//   for (let mainboard of mainboardData) {
//     try {
//       await setDoc(doc(sparePartsRef, mainboard.id), mainboard);
//       console.log(`✅ Uploaded: ${mainboard.title}`);
//     } catch (err) {
//       console.error(`❌ Failed to upload ${mainboard.title}:`, err);
//     }
//   }

//   console.log("🎉 All Mainboard data uploaded!");
// }

// uploadMainboardData();

for (let mainboard of mainboardData) {
  try {
    await setDoc(doc(db, "mainboardData", mainboard.id), mainboard);
    console.log(`✅ Uploaded: ${mainboard.title}`);
  } catch (err) {
    console.error(`❌ Failed to upload ${mainboard.title}:`, err);
  }
}
