import { initializeApp } from "firebase/app";
import { getFirestore, collection, setDoc, doc } from "firebase/firestore";
import { db } from "./firebase-config.js"; // Adjust the import path as necessary

const storageData = [
  {
    id: "storage001",
    title: "Sample Storage Model 1",
    name: "Samsung 970 EVO Plus",
    capacity: "500GB",
    type: "NVMe SSD",
    formFactor: "M.2 2280",
    interface: "PCIe 3.0 x4",
    rating: 4.7,
    price: 79,
    description: "Sample description for storage model 1. High-performance NVMe SSD with excellent read/write speeds for gaming and productivity.",
    imageUrl: "https://example.com/storage1.jpg",
  },
  {
    id: "storage002",
    title: "Sample Storage Model 2",
    name: "Western Digital Blue",
    capacity: "1TB",
    type: "SATA SSD",
    formFactor: "2.5-inch",
    interface: "SATA III",
    rating: 4.3,
    price: 89,
    description: "Sample description for storage model 2. Reliable SATA SSD with good performance for everyday computing tasks.",
    imageUrl: "https://example.com/storage2.jpg",
  },
  {
    id: "storage003",
    title: "Sample Storage Model 3",
    name: "Crucial P5 Plus",
    capacity: "1TB",
    type: "NVMe SSD",
    formFactor: "M.2 2280",
    interface: "PCIe 4.0 x4",
    rating: 4.8,
    price: 129,
    description: "Sample description for storage model 3. Next-generation PCIe 4.0 SSD with blazing-fast speeds for demanding applications.",
    imageUrl: "https://example.com/storage3.jpg",
  },
  {
    id: "storage004",
    title: "Sample Storage Model 4",
    name: "Seagate Barracuda",
    capacity: "2TB",
    type: "HDD",
    formFactor: "3.5-inch",
    interface: "SATA III",
    rating: 4.1,
    price: 49,
    description: "Sample description for storage model 4. High-capacity hard drive for bulk storage and backup purposes.",
    imageUrl: "https://example.com/storage4.jpg",
  },
  {
    id: "storage005",
    title: "Sample Storage Model 5",
    name: "Kingston KC3000",
    capacity: "2TB",
    type: "NVMe SSD",
    formFactor: "M.2 2280",
    interface: "PCIe 4.0 x4",
    rating: 4.6,
    price: 199,
    description: "Sample description for storage model 5. High-capacity NVMe SSD with excellent performance for gaming and content creation.",
    imageUrl: "https://example.com/storage5.jpg",
  },
  {
    id: "storage006",
    title: "Sample Storage Model 6",
    name: "ADATA XPG SX8200 Pro",
    capacity: "1TB",
    type: "NVMe SSD",
    formFactor: "M.2 2280",
    interface: "PCIe 3.0 x4",
    rating: 4.4,
    price: 99,
    description: "Sample description for storage model 6. Gaming-focused NVMe SSD with RGB lighting and high performance.",
    imageUrl: "https://example.com/storage6.jpg",
  },
  {
    id: "storage007",
    title: "Sample Storage Model 7",
    name: "Corsair MP600",
    capacity: "2TB",
    type: "NVMe SSD",
    formFactor: "M.2 2280",
    interface: "PCIe 4.0 x4",
    rating: 4.5,
    price: 249,
    description: "Sample description for storage model 7. High-performance PCIe 4.0 SSD with excellent thermal management.",
    imageUrl: "https://example.com/storage7.jpg",
  },
  {
    id: "storage008",
    title: "Sample Storage Model 8",
    name: "Team Group MP34",
    capacity: "1TB",
    type: "NVMe SSD",
    formFactor: "M.2 2280",
    interface: "PCIe 3.0 x4",
    rating: 4.2,
    price: 89,
    description: "Sample description for storage model 8. Affordable NVMe SSD with good performance for budget builds.",
    imageUrl: "https://example.com/storage8.jpg",
  },
  {
    id: "storage009",
    title: "Sample Storage Model 9",
    name: "Sabrent Rocket 4 Plus",
    capacity: "1TB",
    type: "NVMe SSD",
    formFactor: "M.2 2280",
    interface: "PCIe 4.0 x4",
    rating: 4.7,
    price: 149,
    description: "Sample description for storage model 9. High-speed PCIe 4.0 SSD with excellent reliability and performance.",
    imageUrl: "https://example.com/storage9.jpg",
  },
  {
    id: "storage010",
    title: "Sample Storage Model 10",
    name: "Western Digital Black",
    capacity: "1TB",
    type: "HDD",
    formFactor: "3.5-inch",
    interface: "SATA III",
    rating: 4.3,
    price: 69,
    description: "Sample description for storage model 10. Performance-oriented hard drive for gaming and creative workloads.",
    imageUrl: "https://example.com/storage10.jpg",
  },
  {
    id: "storage011",
    title: "Sample Storage Model 11",
    name: "Samsung 980 Pro",
    capacity: "1TB",
    type: "NVMe SSD",
    formFactor: "M.2 2280",
    interface: "PCIe 4.0 x4",
    rating: 4.9,
    price: 159,
    description: "Sample description for storage model 11. Samsung's flagship PCIe 4.0 SSD with industry-leading performance.",
    imageUrl: "https://example.com/storage11.jpg",
  },
  {
    id: "storage012",
    title: "Sample Storage Model 12",
    name: "Crucial MX500",
    capacity: "2TB",
    type: "SATA SSD",
    formFactor: "2.5-inch",
    interface: "SATA III",
    rating: 4.4,
    price: 179,
    description: "Sample description for storage model 12. High-capacity SATA SSD with excellent reliability and performance.",
    imageUrl: "https://example.com/storage12.jpg",
  },
  {
    id: "storage013",
    title: "Sample Storage Model 13",
    name: "Gigabyte AORUS Gen4",
    capacity: "2TB",
    type: "NVMe SSD",
    formFactor: "M.2 2280",
    interface: "PCIe 4.0 x4",
    rating: 4.6,
    price: 229,
    description: "Sample description for storage model 13. Gaming-focused PCIe 4.0 SSD with RGB lighting and high performance.",
    imageUrl: "https://example.com/storage13.jpg",
  },
  {
    id: "storage014",
    title: "Sample Storage Model 14",
    name: "Seagate FireCuda",
    capacity: "2TB",
    type: "SSHD",
    formFactor: "2.5-inch",
    interface: "SATA III",
    rating: 4.0,
    price: 89,
    description: "Sample description for storage model 14. Hybrid drive combining SSD speed with HDD capacity for laptops.",
    imageUrl: "https://example.com/storage14.jpg",
  },
  {
    id: "storage015",
    title: "Sample Storage Model 15",
    name: "Patriot Viper VPN100",
    capacity: "1TB",
    type: "NVMe SSD",
    formFactor: "M.2 2280",
    interface: "PCIe 3.0 x4",
    rating: 4.3,
    price: 99,
    description: "Sample description for storage model 15. Gaming-focused NVMe SSD with RGB lighting and good performance.",
    imageUrl: "https://example.com/storage15.jpg",
  },
  {
    id: "storage016",
    title: "Sample Storage Model 16",
    name: "Kingston A2000",
    capacity: "1TB",
    type: "NVMe SSD",
    formFactor: "M.2 2280",
    interface: "PCIe 3.0 x4",
    rating: 4.2,
    price: 89,
    description: "Sample description for storage model 16. Budget-friendly NVMe SSD with reliable performance for everyday use.",
    imageUrl: "https://example.com/storage16.jpg",
  },
  {
    id: "storage017",
    title: "Sample Storage Model 17",
    name: "ADATA Ultimate SU800",
    capacity: "1TB",
    type: "SATA SSD",
    formFactor: "2.5-inch",
    interface: "SATA III",
    rating: 4.1,
    price: 79,
    description: "Sample description for storage model 17. Reliable SATA SSD with good performance for budget-conscious users.",
    imageUrl: "https://example.com/storage17.jpg",
  },
  {
    id: "storage018",
    title: "Sample Storage Model 18",
    name: "Corsair Force MP510",
    capacity: "960GB",
    type: "NVMe SSD",
    formFactor: "M.2 2280",
    interface: "PCIe 3.0 x4",
    rating: 4.4,
    price: 119,
    description: "Sample description for storage model 18. High-performance NVMe SSD with excellent endurance and reliability.",
    imageUrl: "https://example.com/storage18.jpg",
  },
  {
    id: "storage019",
    title: "Sample Storage Model 19",
    name: "Team Group T-Force Cardea",
    capacity: "1TB",
    type: "NVMe SSD",
    formFactor: "M.2 2280",
    interface: "PCIe 4.0 x4",
    rating: 4.5,
    price: 139,
    description: "Sample description for storage model 19. PCIe 4.0 SSD with RGB lighting and excellent gaming performance.",
    imageUrl: "https://example.com/storage19.jpg",
  },
  {
    id: "storage020",
    title: "Sample Storage Model 20",
    name: "Western Digital Red",
    capacity: "4TB",
    type: "HDD",
    formFactor: "3.5-inch",
    interface: "SATA III",
    rating: 4.2,
    price: 99,
    description: "Sample description for storage model 20. NAS-optimized hard drive for network storage and backup solutions.",
    imageUrl: "https://example.com/storage20.jpg",
  },
  {
    id: "storage021",
    title: "Sample Storage Model 21",
    name: "Samsung 870 EVO",
    capacity: "1TB",
    type: "SATA SSD",
    formFactor: "2.5-inch",
    interface: "SATA III",
    rating: 4.6,
    price: 109,
    description: "Sample description for storage model 21. Samsung's latest SATA SSD with improved performance and reliability.",
    imageUrl: "https://example.com/storage21.jpg",
  },
  {
    id: "storage022",
    title: "Sample Storage Model 22",
    name: "Crucial P2",
    capacity: "1TB",
    type: "NVMe SSD",
    formFactor: "M.2 2280",
    interface: "PCIe 3.0 x4",
    rating: 4.0,
    price: 79,
    description: "Sample description for storage model 22. Budget NVMe SSD with good performance for entry-level builds.",
    imageUrl: "https://example.com/storage22.jpg",
  },
  {
    id: "storage023",
    title: "Sample Storage Model 23",
    name: "Seagate IronWolf",
    capacity: "6TB",
    type: "HDD",
    formFactor: "3.5-inch",
    interface: "SATA III",
    rating: 4.3,
    price: 149,
    description: "Sample description for storage model 23. NAS-optimized hard drive with high capacity for server applications.",
    imageUrl: "https://example.com/storage23.jpg",
  },
  {
    id: "storage024",
    title: "Sample Storage Model 24",
    name: "Kingston KC2500",
    capacity: "1TB",
    type: "NVMe SSD",
    formFactor: "M.2 2280",
    interface: "PCIe 3.0 x4",
    rating: 4.5,
    price: 119,
    description: "Sample description for storage model 24. High-performance NVMe SSD with excellent reliability for professional use.",
    imageUrl: "https://example.com/storage24.jpg",
  },
  {
    id: "storage025",
    title: "Sample Storage Model 25",
    name: "ADATA Swordfish",
    capacity: "1TB",
    type: "NVMe SSD",
    formFactor: "M.2 2280",
    interface: "PCIe 3.0 x4",
    rating: 4.1,
    price: 89,
    description: "Sample description for storage model 25. Gaming-focused NVMe SSD with good performance and affordability.",
    imageUrl: "https://example.com/storage25.jpg",
  },
  {
    id: "storage026",
    title: "Sample Storage Model 26",
    name: "Corsair Force Series MP600",
    capacity: "1TB",
    type: "NVMe SSD",
    formFactor: "M.2 2280",
    interface: "PCIe 4.0 x4",
    rating: 4.7,
    price: 169,
    description: "Sample description for storage model 26. High-performance PCIe 4.0 SSD with excellent thermal design.",
    imageUrl: "https://example.com/storage26.jpg",
  },
  {
    id: "storage027",
    title: "Sample Storage Model 27",
    name: "Team Group MP33",
    capacity: "1TB",
    type: "NVMe SSD",
    formFactor: "M.2 2280",
    interface: "PCIe 3.0 x4",
    rating: 4.0,
    price: 79,
    description: "Sample description for storage model 27. Budget-friendly NVMe SSD with reliable performance for everyday computing.",
    imageUrl: "https://example.com/storage27.jpg",
  },
  {
    id: "storage028",
    title: "Sample Storage Model 28",
    name: "Sabrent Rocket Q",
    capacity: "2TB",
    type: "NVMe SSD",
    formFactor: "M.2 2280",
    interface: "PCIe 3.0 x4",
    rating: 4.4,
    price: 199,
    description: "Sample description for storage model 28. High-capacity NVMe SSD with QLC technology for cost-effective storage.",
    imageUrl: "https://example.com/storage28.jpg",
  },
  {
    id: "storage029",
    title: "Sample Storage Model 29",
    name: "Western Digital SN750",
    capacity: "1TB",
    type: "NVMe SSD",
    formFactor: "M.2 2280",
    interface: "PCIe 3.0 x4",
    rating: 4.6,
    price: 129,
    description: "Sample description for storage model 29. Gaming-focused NVMe SSD with excellent performance and reliability.",
    imageUrl: "https://example.com/storage29.jpg",
  },
  {
    id: "storage030",
    title: "Sample Storage Model 30",
    name: "Samsung 860 EVO",
    capacity: "2TB",
    type: "SATA SSD",
    formFactor: "2.5-inch",
    interface: "SATA III",
    rating: 4.5,
    price: 199,
    description: "Sample description for storage model 30. High-capacity SATA SSD with excellent performance and reliability for bulk storage.",
    imageUrl: "https://example.com/storage30.jpg",
  },
];

// async function uploadStorageData() {
//   const sparePartsRef = collection(db, "SparePart");

//   for (let storage of storageData) {
//     try {
//       await setDoc(doc(sparePartsRef, storage.id), storage);
//       console.log(`✅ Uploaded: ${storage.title}`);
//     } catch (err) {
//       console.error(`❌ Failed to upload ${storage.title}:`, err);
//     }
//   }

//   console.log("🎉 All Storage data uploaded!");
// }

// uploadStorageData();

for (let storage of storageData) {
  try {
    await setDoc(doc(db, "storageData", storage.id), storage);
    console.log(`✅ Uploaded: ${storage.title}`);
  } catch (err) {
    console.error(`❌ Failed to upload ${storage.title}:`, err);
  }
} 