import { initializeApp } from "firebase/app";
import { getFirestore, collection, setDoc, doc } from "firebase/firestore";
import { db } from "./firebase-config.js"; // Adjust the import path as necessary

const caseData = [
  {
    id: "case001",
    title: "Sample Case Model 1",
    name: "NZXT H510",
    Type: "Mid Tower",
    color: "Black",
    sidePanel: "Tempered Glass",
    externalVolume: "46.08L",
    internal35Bays: 2,
    rating: 4.3,
    price: 89,
    description: "Sample description for case model 1. Clean and minimalist mid-tower case with excellent airflow and cable management.",
    imageUrl: "https://example.com/case1.jpg",
  },
  {
    id: "case002",
    title: "Sample Case Model 2",
    name: "Corsair 4000D Airflow",
    Type: "Mid Tower",
    color: "Black",
    sidePanel: "Tempered Glass",
    externalVolume: "45.4L",
    internal35Bays: 2,
    rating: 4.5,
    price: 94,
    description: "Sample description for case model 2. High-airflow mid-tower case with excellent thermal performance and modern design.",
    imageUrl: "https://example.com/case2.jpg",
  },
  {
    id: "case003",
    title: "Sample Case Model 3",
    name: "Phanteks P400A",
    Type: "Mid Tower",
    color: "Black",
    sidePanel: "Tempered Glass",
    externalVolume: "43.2L",
    internal35Bays: 2,
    rating: 4.2,
    price: 79,
    description: "Sample description for case model 3. Affordable mid-tower case with good airflow and RGB lighting support.",
    imageUrl: "https://example.com/case3.jpg",
  },
  {
    id: "case004",
    title: "Sample Case Model 4",
    name: "Lian Li O11 Dynamic",
    Type: "Full Tower",
    color: "Black",
    sidePanel: "Tempered Glass",
    externalVolume: "58.5L",
    internal35Bays: 3,
    rating: 4.7,
    price: 149,
    description: "Sample description for case model 4. Premium full-tower case with exceptional build quality and extensive water cooling support.",
    imageUrl: "https://example.com/case4.jpg",
  },
  {
    id: "case005",
    title: "Sample Case Model 5",
    name: "Fractal Design Meshify C",
    Type: "Mid Tower",
    color: "Black",
    sidePanel: "Tempered Glass",
    externalVolume: "39.5L",
    internal35Bays: 2,
    rating: 4.4,
    price: 89,
    description: "Sample description for case model 5. Compact mid-tower case with mesh front panel for excellent airflow and noise reduction.",
    imageUrl: "https://example.com/case5.jpg",
  },
  {
    id: "case006",
    title: "Sample Case Model 6",
    name: "be quiet! Pure Base 500DX",
    Type: "Mid Tower",
    color: "Black",
    sidePanel: "Tempered Glass",
    externalVolume: "45.8L",
    internal35Bays: 2,
    rating: 4.3,
    price: 99,
    description: "Sample description for case model 6. Silent-focused mid-tower case with excellent noise dampening and RGB lighting.",
    imageUrl: "https://example.com/case6.jpg",
  },
  {
    id: "case007",
    title: "Sample Case Model 7",
    name: "Cooler Master H500",
    Type: "Mid Tower",
    color: "Black",
    sidePanel: "Tempered Glass",
    externalVolume: "47.2L",
    internal35Bays: 2,
    rating: 4.1,
    price: 109,
    description: "Sample description for case model 7. Gaming-focused mid-tower case with dual 200mm RGB fans and excellent airflow.",
    imageUrl: "https://example.com/case7.jpg",
  },
  {
    id: "case008",
    title: "Sample Case Model 8",
    name: "NZXT H710",
    Type: "Mid Tower",
    color: "Black",
    sidePanel: "Tempered Glass",
    externalVolume: "52.4L",
    internal35Bays: 3,
    rating: 4.2,
    price: 139,
    description: "Sample description for case model 8. Premium mid-tower case with excellent cable management and water cooling support.",
    imageUrl: "https://example.com/case8.jpg",
  },
  {
    id: "case009",
    title: "Sample Case Model 9",
    name: "Corsair 5000D Airflow",
    Type: "Full Tower",
    color: "Black",
    sidePanel: "Tempered Glass",
    externalVolume: "58.5L",
    internal35Bays: 4,
    rating: 4.6,
    price: 174,
    description: "Sample description for case model 9. High-performance full-tower case with exceptional airflow and extensive cooling options.",
    imageUrl: "https://example.com/case9.jpg",
  },
  {
    id: "case010",
    title: "Sample Case Model 10",
    name: "Phanteks Enthoo 719",
    Type: "Full Tower",
    color: "Black",
    sidePanel: "Tempered Glass",
    externalVolume: "75.2L",
    internal35Bays: 6,
    rating: 4.8,
    price: 249,
    description: "Sample description for case model 10. Massive full-tower case designed for extreme builds with dual system support.",
    imageUrl: "https://example.com/case10.jpg",
  },
  {
    id: "case011",
    title: "Sample Case Model 11",
    name: "Lian Li Q58",
    Type: "Mini-ITX",
    color: "Black",
    sidePanel: "Tempered Glass",
    externalVolume: "14.6L",
    internal35Bays: 1,
    rating: 4.4,
    price: 119,
    description: "Sample description for case model 11. Compact mini-ITX case with dual-chamber design and excellent thermal performance.",
    imageUrl: "https://example.com/case11.jpg",
  },
  {
    id: "case012",
    title: "Sample Case Model 12",
    name: "Fractal Design Node 202",
    Type: "Mini-ITX",
    color: "Black",
    sidePanel: "Steel",
    externalVolume: "10.2L",
    internal35Bays: 2,
    rating: 4.0,
    price: 79,
    description: "Sample description for case model 12. Console-style mini-ITX case perfect for living room gaming setups.",
    imageUrl: "https://example.com/case12.jpg",
  },
  {
    id: "case013",
    title: "Sample Case Model 13",
    name: "NZXT H1",
    Type: "Mini-ITX",
    color: "Black",
    sidePanel: "Tempered Glass",
    externalVolume: "13.6L",
    internal35Bays: 1,
    rating: 4.3,
    price: 349,
    description: "Sample description for case model 13. Premium mini-ITX case with integrated AIO cooler and SFX power supply.",
    imageUrl: "https://example.com/case13.jpg",
  },
  {
    id: "case014",
    title: "Sample Case Model 14",
    name: "Cooler Master NR200",
    Type: "Mini-ITX",
    color: "Black",
    sidePanel: "Steel",
    externalVolume: "18.2L",
    internal35Bays: 2,
    rating: 4.5,
    price: 89,
    description: "Sample description for case model 14. Versatile mini-ITX case with excellent airflow and water cooling support.",
    imageUrl: "https://example.com/case14.jpg",
  },
  {
    id: "case015",
    title: "Sample Case Model 15",
    name: "Phanteks Evolv Shift Air",
    Type: "Mini-ITX",
    color: "Black",
    sidePanel: "Tempered Glass",
    externalVolume: "19.8L",
    internal35Bays: 1,
    rating: 4.1,
    price: 109,
    description: "Sample description for case model 15. Vertical mini-ITX case with unique design and good thermal performance.",
    imageUrl: "https://example.com/case15.jpg",
  },
  {
    id: "case016",
    title: "Sample Case Model 16",
    name: "Corsair 280X",
    Type: "Micro-ATX",
    color: "Black",
    sidePanel: "Tempered Glass",
    externalVolume: "44.8L",
    internal35Bays: 2,
    rating: 4.2,
    price: 119,
    description: "Sample description for case model 16. Dual-chamber micro-ATX case with excellent cable management and RGB support.",
    imageUrl: "https://example.com/case16.jpg",
  },
  {
    id: "case017",
    title: "Sample Case Model 17",
    name: "Fractal Design Define Mini C",
    Type: "Micro-ATX",
    color: "Black",
    sidePanel: "Steel",
    externalVolume: "32.4L",
    internal35Bays: 2,
    rating: 4.0,
    price: 79,
    description: "Sample description for case model 17. Silent-focused micro-ATX case with excellent noise dampening and good airflow.",
    imageUrl: "https://example.com/case17.jpg",
  },
  {
    id: "case018",
    title: "Sample Case Model 18",
    name: "NZXT H400",
    Type: "Micro-ATX",
    color: "Black",
    sidePanel: "Tempered Glass",
    externalVolume: "36.8L",
    internal35Bays: 2,
    rating: 4.1,
    price: 99,
    description: "Sample description for case model 18. Compact micro-ATX case with clean design and excellent cable management.",
    imageUrl: "https://example.com/case18.jpg",
  },
  {
    id: "case019",
    title: "Sample Case Model 19",
    name: "be quiet! Pure Base 600",
    Type: "Mid Tower",
    color: "Black",
    sidePanel: "Steel",
    externalVolume: "48.2L",
    internal35Bays: 3,
    rating: 4.3,
    price: 89,
    description: "Sample description for case model 19. Silent mid-tower case with excellent noise dampening and modular design.",
    imageUrl: "https://example.com/case19.jpg",
  },
  {
    id: "case020",
    title: "Sample Case Model 20",
    name: "Cooler Master MasterBox Q300L",
    Type: "Micro-ATX",
    color: "Black",
    sidePanel: "Acrylic",
    externalVolume: "23.4L",
    internal35Bays: 2,
    rating: 3.8,
    price: 49,
    description: "Sample description for case model 20. Budget-friendly micro-ATX case with modular design and good airflow.",
    imageUrl: "https://example.com/case20.jpg",
  },
  {
    id: "case021",
    title: "Sample Case Model 21",
    name: "Phanteks P300A",
    Type: "Mid Tower",
    color: "Black",
    sidePanel: "Tempered Glass",
    externalVolume: "40.8L",
    internal35Bays: 2,
    rating: 4.0,
    price: 69,
    description: "Sample description for case model 21. Affordable mid-tower case with mesh front panel and good thermal performance.",
    imageUrl: "https://example.com/case21.jpg",
  },
  {
    id: "case022",
    title: "Sample Case Model 22",
    name: "Corsair 275R Airflow",
    Type: "Mid Tower",
    color: "Black",
    sidePanel: "Tempered Glass",
    externalVolume: "45.2L",
    internal35Bays: 2,
    rating: 4.1,
    price: 79,
    description: "Sample description for case model 22. High-airflow mid-tower case with clean design and excellent cooling potential.",
    imageUrl: "https://example.com/case22.jpg",
  },
  {
    id: "case023",
    title: "Sample Case Model 23",
    name: "Fractal Design Define R6",
    Type: "Mid Tower",
    color: "Black",
    sidePanel: "Steel",
    externalVolume: "52.8L",
    internal35Bays: 3,
    rating: 4.4,
    price: 129,
    description: "Sample description for case model 23. Versatile mid-tower case with modular design and excellent water cooling support.",
    imageUrl: "https://example.com/case23.jpg",
  },
  {
    id: "case024",
    title: "Sample Case Model 24",
    name: "NZXT H210",
    Type: "Mini-ITX",
    color: "Black",
    sidePanel: "Tempered Glass",
    externalVolume: "27.4L",
    internal35Bays: 2,
    rating: 4.2,
    price: 79,
    description: "Sample description for case model 24. Compact mini-ITX case with clean design and excellent cable management.",
    imageUrl: "https://example.com/case24.jpg",
  },
  {
    id: "case025",
    title: "Sample Case Model 25",
    name: "Lian Li PC-O11 Dynamic",
    Type: "Full Tower",
    color: "White",
    sidePanel: "Tempered Glass",
    externalVolume: "58.5L",
    internal35Bays: 3,
    rating: 4.7,
    price: 159,
    description: "Sample description for case model 25. Premium white full-tower case with exceptional build quality and extensive water cooling support.",
    imageUrl: "https://example.com/case25.jpg",
  },
  {
    id: "case026",
    title: "Sample Case Model 26",
    name: "be quiet! Dark Base Pro 900",
    Type: "Full Tower",
    color: "Black",
    sidePanel: "Tempered Glass",
    externalVolume: "68.4L",
    internal35Bays: 5,
    rating: 4.6,
    price: 269,
    description: "Sample description for case model 26. Premium full-tower case with exceptional noise dampening and modular design.",
    imageUrl: "https://example.com/case26.jpg",
  },
  {
    id: "case027",
    title: "Sample Case Model 27",
    name: "Cooler Master Cosmos C700M",
    Type: "Full Tower",
    color: "Black",
    sidePanel: "Tempered Glass",
    externalVolume: "82.6L",
    internal35Bays: 6,
    rating: 4.8,
    price: 399,
    description: "Sample description for case model 27. Luxury full-tower case with premium materials and extensive customization options.",
    imageUrl: "https://example.com/case27.jpg",
  },
  {
    id: "case028",
    title: "Sample Case Model 28",
    name: "Phanteks Enthoo 719",
    Type: "Full Tower",
    color: "White",
    sidePanel: "Tempered Glass",
    externalVolume: "75.2L",
    internal35Bays: 6,
    rating: 4.8,
    price: 269,
    description: "Sample description for case model 28. Massive white full-tower case designed for extreme builds with dual system support.",
    imageUrl: "https://example.com/case28.jpg",
  },
  {
    id: "case029",
    title: "Sample Case Model 29",
    name: "Corsair Obsidian 1000D",
    Type: "Super Tower",
    color: "Black",
    sidePanel: "Tempered Glass",
    externalVolume: "95.2L",
    internal35Bays: 8,
    rating: 4.9,
    price: 499,
    description: "Sample description for case model 29. Ultimate super tower case with dual system support and extensive water cooling capabilities.",
    imageUrl: "https://example.com/case29.jpg",
  },
  {
    id: "case030",
    title: "Sample Case Model 30",
    name: "Fractal Design Torrent",
    Type: "Mid Tower",
    color: "Black",
    sidePanel: "Tempered Glass",
    externalVolume: "54.8L",
    internal35Bays: 3,
    rating: 4.7,
    price: 189,
    description: "Sample description for case model 30. Innovative mid-tower case with bottom-mounted fans for exceptional airflow and cooling performance.",
    imageUrl: "https://example.com/case30.jpg",
  },
];

// async function uploadCaseData() {
//   const sparePartsRef = collection(db, "SparePart");

//   for (let caseItem of caseData) {
//     try {
//       await setDoc(doc(sparePartsRef, caseItem.id), caseItem);
//       console.log(`✅ Uploaded: ${caseItem.title}`);
//     } catch (err) {
//       console.error(`❌ Failed to upload ${caseItem.title}:`, err);
//     }
//   }

//   console.log("🎉 All Case data uploaded!");
// }

// uploadCaseData();

for (let caseItem of caseData) {
  try {
    await setDoc(doc(db, "caseData", caseItem.id), caseItem);
    console.log(`✅ Uploaded: ${caseItem.title}`);
  } catch (err) {
    console.error(`❌ Failed to upload ${caseItem.title}:`, err);
  }
} 