import { initializeApp } from "firebase/app";
import { getFirestore, collection, setDoc, doc } from "firebase/firestore";
import { db } from "./firebase-config.js"; // Adjust the import path as necessary

const gpuData = [
  {
    id: "gpu001",
    title: "Sample GPU Model 1",
    chipset: "RTX 4060",
    memory: "8GB GDDR6",
    coreClock: "2.4GHz",
    length: "242mm",
    rating: 4.2,
    price: 299,
    description: "Sample description for GPU model 1. Great for 1080p gaming and content creation.",
    imageUrl: "https://example.com/gpu1.jpg",
  },
  {
    id: "gpu002",
    title: "Sample GPU Model 2",
    chipset: "RX 7600",
    memory: "8GB GDDR6",
    coreClock: "2.6GHz",
    length: "248mm",
    rating: 4.0,
    price: 269,
    description: "Sample description for GPU model 2. Excellent performance for 1080p gaming.",
    imageUrl: "https://example.com/gpu2.jpg",
  },
  {
    id: "gpu003",
    title: "Sample GPU Model 3",
    chipset: "RTX 4070",
    memory: "12GB GDDR6X",
    coreClock: "2.5GHz",
    length: "285mm",
    rating: 4.5,
    price: 599,
    description: "Sample description for GPU model 3. Perfect for 1440p gaming and ray tracing.",
    imageUrl: "https://example.com/gpu3.jpg",
  },
  {
    id: "gpu004",
    title: "Sample GPU Model 4",
    chipset: "RX 7700 XT",
    memory: "12GB GDDR6",
    coreClock: "2.7GHz",
    length: "287mm",
    rating: 4.3,
    price: 449,
    description: "Sample description for GPU model 4. Great value for 1440p gaming performance.",
    imageUrl: "https://example.com/gpu4.jpg",
  },
  {
    id: "gpu005",
    title: "Sample GPU Model 5",
    chipset: "RTX 4080",
    memory: "16GB GDDR6X",
    coreClock: "2.5GHz",
    length: "304mm",
    rating: 4.7,
    price: 1199,
    description: "Sample description for GPU model 5. High-end performance for 4K gaming.",
    imageUrl: "https://example.com/gpu5.jpg",
  },
  {
    id: "gpu006",
    title: "Sample GPU Model 6",
    chipset: "RX 7800 XT",
    memory: "16GB GDDR6",
    coreClock: "2.6GHz",
    length: "287mm",
    rating: 4.4,
    price: 499,
    description: "Sample description for GPU model 6. Excellent 1440p and 4K gaming performance.",
    imageUrl: "https://example.com/gpu6.jpg",
  },
  {
    id: "gpu007",
    title: "Sample GPU Model 7",
    chipset: "RTX 4090",
    memory: "24GB GDDR6X",
    coreClock: "2.5GHz",
    length: "304mm",
    rating: 4.9,
    price: 1599,
    description: "Sample description for GPU model 7. Ultimate gaming performance for 4K and beyond.",
    imageUrl: "https://example.com/gpu7.jpg",
  },
  {
    id: "gpu008",
    title: "Sample GPU Model 8",
    chipset: "RX 7900 XT",
    memory: "20GB GDDR6",
    coreClock: "2.4GHz",
    length: "287mm",
    rating: 4.6,
    price: 799,
    description: "Sample description for GPU model 8. High-end AMD performance for demanding games.",
    imageUrl: "https://example.com/gpu8.jpg",
  },
  {
    id: "gpu009",
    title: "Sample GPU Model 9",
    chipset: "RTX 4070 Ti",
    memory: "12GB GDDR6X",
    coreClock: "2.6GHz",
    length: "285mm",
    rating: 4.4,
    price: 799,
    description: "Sample description for GPU model 9. Great balance of performance and price.",
    imageUrl: "https://example.com/gpu9.jpg",
  },
  {
    id: "gpu010",
    title: "Sample GPU Model 10",
    chipset: "RX 7900 XTX",
    memory: "24GB GDDR6",
    coreClock: "2.5GHz",
    length: "287mm",
    rating: 4.8,
    price: 999,
    description: "Sample description for GPU model 10. AMD's flagship gaming GPU.",
    imageUrl: "https://example.com/gpu10.jpg",
  },
  {
    id: "gpu011",
    title: "Sample GPU Model 11",
    chipset: "RTX 4060 Ti",
    memory: "8GB GDDR6",
    coreClock: "2.5GHz",
    length: "242mm",
    rating: 4.1,
    price: 399,
    description: "Sample description for GPU model 11. Mid-range performance with ray tracing.",
    imageUrl: "https://example.com/gpu11.jpg",
  },
  {
    id: "gpu012",
    title: "Sample GPU Model 12",
    chipset: "RX 7600 XT",
    memory: "8GB GDDR6",
    coreClock: "2.7GHz",
    length: "248mm",
    rating: 4.0,
    price: 329,
    description: "Sample description for GPU model 12. AMD's mid-range gaming solution.",
    imageUrl: "https://example.com/gpu12.jpg",
  },
  {
    id: "gpu013",
    title: "Sample GPU Model 13",
    chipset: "RTX 3080",
    memory: "10GB GDDR6X",
    coreClock: "1.7GHz",
    length: "285mm",
    rating: 4.3,
    price: 699,
    description: "Sample description for GPU model 13. Previous generation high-end performance.",
    imageUrl: "https://example.com/gpu13.jpg",
  },
  {
    id: "gpu014",
    title: "Sample GPU Model 14",
    chipset: "RX 6800 XT",
    memory: "16GB GDDR6",
    coreClock: "2.2GHz",
    length: "267mm",
    rating: 4.2,
    price: 649,
    description: "Sample description for GPU model 14. AMD's previous generation flagship.",
    imageUrl: "https://example.com/gpu14.jpg",
  },
  {
    id: "gpu015",
    title: "Sample GPU Model 15",
    chipset: "RTX 3070",
    memory: "8GB GDDR6",
    coreClock: "1.7GHz",
    length: "242mm",
    rating: 4.0,
    price: 499,
    description: "Sample description for GPU model 15. Popular mid-range gaming GPU.",
    imageUrl: "https://example.com/gpu15.jpg",
  },
  {
    id: "gpu016",
    title: "Sample GPU Model 16",
    chipset: "RX 6700 XT",
    memory: "12GB GDDR6",
    coreClock: "2.4GHz",
    length: "267mm",
    rating: 4.1,
    price: 379,
    description: "Sample description for GPU model 16. Great 1440p gaming performance.",
    imageUrl: "https://example.com/gpu16.jpg",
  },
  {
    id: "gpu017",
    title: "Sample GPU Model 17",
    chipset: "RTX 3060 Ti",
    memory: "8GB GDDR6",
    coreClock: "1.6GHz",
    length: "242mm",
    rating: 4.2,
    price: 399,
    description: "Sample description for GPU model 17. Excellent value for 1440p gaming.",
    imageUrl: "https://example.com/gpu17.jpg",
  },
  {
    id: "gpu018",
    title: "Sample GPU Model 18",
    chipset: "RX 6600 XT",
    memory: "8GB GDDR6",
    coreClock: "2.6GHz",
    length: "242mm",
    rating: 3.9,
    price: 379,
    description: "Sample description for GPU model 18. Solid 1080p gaming performance.",
    imageUrl: "https://example.com/gpu18.jpg",
  },
  {
    id: "gpu019",
    title: "Sample GPU Model 19",
    chipset: "RTX 3060",
    memory: "12GB GDDR6",
    coreClock: "1.7GHz",
    length: "242mm",
    rating: 4.0,
    price: 329,
    description: "Sample description for GPU model 19. Entry-level ray tracing capable GPU.",
    imageUrl: "https://example.com/gpu19.jpg",
  },
  {
    id: "gpu020",
    title: "Sample GPU Model 20",
    chipset: "RX 6600",
    memory: "8GB GDDR6",
    coreClock: "2.4GHz",
    length: "190mm",
    rating: 3.8,
    price: 329,
    description: "Sample description for GPU model 20. Compact gaming solution.",
    imageUrl: "https://example.com/gpu20.jpg",
  },
  {
    id: "gpu021",
    title: "Sample GPU Model 21",
    chipset: "GTX 1660 Super",
    memory: "6GB GDDR6",
    coreClock: "1.7GHz",
    length: "229mm",
    rating: 3.7,
    price: 229,
    description: "Sample description for GPU model 21. Budget-friendly gaming option.",
    imageUrl: "https://example.com/gpu21.jpg",
  },
  {
    id: "gpu022",
    title: "Sample GPU Model 22",
    chipset: "RX 6500 XT",
    memory: "4GB GDDR6",
    coreClock: "2.8GHz",
    length: "190mm",
    rating: 3.5,
    price: 199,
    description: "Sample description for GPU model 22. Entry-level gaming GPU.",
    imageUrl: "https://example.com/gpu22.jpg",
  },
  {
    id: "gpu023",
    title: "Sample GPU Model 23",
    chipset: "RTX 3050",
    memory: "8GB GDDR6",
    coreClock: "1.7GHz",
    length: "242mm",
    rating: 3.8,
    price: 249,
    description: "Sample description for GPU model 23. Affordable ray tracing entry point.",
    imageUrl: "https://example.com/gpu23.jpg",
  },
  {
    id: "gpu024",
    title: "Sample GPU Model 24",
    chipset: "RX 6400",
    memory: "4GB GDDR6",
    coreClock: "2.3GHz",
    length: "167mm",
    rating: 3.3,
    price: 159,
    description: "Sample description for GPU model 24. Ultra-compact gaming solution.",
    imageUrl: "https://example.com/gpu24.jpg",
  },
  {
    id: "gpu025",
    title: "Sample GPU Model 25",
    chipset: "GTX 1650",
    memory: "4GB GDDR6",
    coreClock: "1.5GHz",
    length: "229mm",
    rating: 3.4,
    price: 179,
    description: "Sample description for GPU model 25. Basic gaming performance.",
    imageUrl: "https://example.com/gpu25.jpg",
  },
  {
    id: "gpu026",
    title: "Sample GPU Model 26",
    chipset: "RTX 2080 Ti",
    memory: "11GB GDDR6",
    coreClock: "1.5GHz",
    length: "267mm",
    rating: 4.1,
    price: 999,
    description: "Sample description for GPU model 26. Previous generation flagship performance.",
    imageUrl: "https://example.com/gpu26.jpg",
  },
  {
    id: "gpu027",
    title: "Sample GPU Model 27",
    chipset: "RX 5700 XT",
    memory: "8GB GDDR6",
    coreClock: "1.9GHz",
    length: "267mm",
    rating: 3.9,
    price: 399,
    description: "Sample description for GPU model 27. Previous generation AMD performance.",
    imageUrl: "https://example.com/gpu27.jpg",
  },
  {
    id: "gpu028",
    title: "Sample GPU Model 28",
    chipset: "RTX 2070 Super",
    memory: "8GB GDDR6",
    coreClock: "1.6GHz",
    length: "267mm",
    rating: 3.8,
    price: 499,
    description: "Sample description for GPU model 28. Previous generation mid-range.",
    imageUrl: "https://example.com/gpu28.jpg",
  },
  {
    id: "gpu029",
    title: "Sample GPU Model 29",
    chipset: "RX 5600 XT",
    memory: "6GB GDDR6",
    coreClock: "1.7GHz",
    length: "242mm",
    rating: 3.7,
    price: 279,
    description: "Sample description for GPU model 29. Previous generation budget option.",
    imageUrl: "https://example.com/gpu29.jpg",
  },
  {
    id: "gpu030",
    title: "Sample GPU Model 30",
    chipset: "GTX 1080 Ti",
    memory: "11GB GDDR5X",
    coreClock: "1.4GHz",
    length: "267mm",
    rating: 3.9,
    price: 699,
    description: "Sample description for GPU model 30. Classic high-end gaming performance.",
    imageUrl: "https://example.com/gpu30.jpg",
  },
];

// async function uploadGPUData() {
//   const sparePartsRef = collection(db, "SparePart");

//   for (let gpu of gpuData) {
//     try {
//       await setDoc(doc(sparePartsRef, gpu.id), gpu);
//       console.log(`✅ Uploaded: ${gpu.title}`);
//     } catch (err) {
//       console.error(`❌ Failed to upload ${gpu.title}:`, err);
//     }
//   }

//   console.log("🎉 All GPU data uploaded!");
// }

// uploadGPUData();

for (let gpu of gpuData) {
  try {
    await setDoc(doc(db, "gpuData", gpu.id), gpu);
    console.log(`✅ Uploaded: ${gpu.title}`);
  } catch (err) {
    console.error(`❌ Failed to upload ${gpu.title}:`, err);
  }
}
