import { initializeApp } from "firebase/app";
import { getFirestore, collection, setDoc, doc } from "firebase/firestore";
import { db } from "./firebase-config.js"; // Adjust the import path as necessary

const cpuCoolerData = [
  {
    id: "cooler001",
    title: "Sample CPU Cooler Model 1",
    name: "Noctua NH-D15",
    fanRPM: "1500",
    noiseLevel: "24.6 dB",
    radiatorSize: "140mm",
    rating: 4.8,
    price: 99,
    description: "Sample description for CPU cooler model 1. Premium air cooler with dual 140mm fans and excellent thermal performance for high-end CPUs.",
    imageUrl: "https://example.com/cooler1.jpg",
  },
  {
    id: "cooler002",
    title: "Sample CPU Cooler Model 2",
    name: "Corsair H100i RGB Pro XT",
    fanRPM: "2400",
    noiseLevel: "28 dB",
    radiatorSize: "240mm",
    rating: 4.5,
    price: 119,
    description: "Sample description for CPU cooler model 2. High-performance liquid cooler with RGB lighting and excellent cooling capacity.",
    imageUrl: "https://example.com/cooler2.jpg",
  },
  {
    id: "cooler003",
    title: "Sample CPU Cooler Model 3",
    name: "be quiet! Dark Rock Pro 4",
    fanRPM: "1500",
    noiseLevel: "24.3 dB",
    radiatorSize: "135mm",
    rating: 4.6,
    price: 89,
    description: "Sample description for CPU cooler model 3. Silent air cooler with excellent thermal performance and low noise operation.",
    imageUrl: "https://example.com/cooler3.jpg",
  },
  {
    id: "cooler004",
    title: "Sample CPU Cooler Model 4",
    name: "NZXT Kraken X53",
    fanRPM: "1800",
    noiseLevel: "27 dB",
    radiatorSize: "240mm",
    rating: 4.4,
    price: 129,
    description: "Sample description for CPU cooler model 4. Premium liquid cooler with CAM software control and excellent aesthetics.",
    imageUrl: "https://example.com/cooler4.jpg",
  },
  {
    id: "cooler005",
    title: "Sample CPU Cooler Model 5",
    name: "Cooler Master Hyper 212 EVO",
    fanRPM: "2000",
    noiseLevel: "32 dB",
    radiatorSize: "120mm",
    rating: 4.2,
    price: 39,
    description: "Sample description for CPU cooler model 5. Popular budget air cooler with good performance and affordable price.",
    imageUrl: "https://example.com/cooler5.jpg",
  },
  {
    id: "cooler006",
    title: "Sample CPU Cooler Model 6",
    name: "Arctic Liquid Freezer II 280",
    fanRPM: "2000",
    noiseLevel: "22.5 dB",
    radiatorSize: "280mm",
    rating: 4.7,
    price: 109,
    description: "Sample description for CPU cooler model 6. High-performance liquid cooler with excellent noise levels and thermal performance.",
    imageUrl: "https://example.com/cooler6.jpg",
  },
  {
    id: "cooler007",
    title: "Sample CPU Cooler Model 7",
    name: "DeepCool AK620",
    fanRPM: "1850",
    noiseLevel: "29 dB",
    radiatorSize: "120mm",
    rating: 4.3,
    price: 64,
    description: "Sample description for CPU cooler model 7. Dual-tower air cooler with good performance and competitive pricing.",
    imageUrl: "https://example.com/cooler7.jpg",
  },
  {
    id: "cooler008",
    title: "Sample CPU Cooler Model 8",
    name: "Corsair H150i Elite Capellix",
    fanRPM: "2400",
    noiseLevel: "28 dB",
    radiatorSize: "360mm",
    rating: 4.6,
    price: 189,
    price: 189,
    description: "Sample description for CPU cooler model 8. Premium 360mm liquid cooler with RGB lighting and excellent cooling performance.",
    imageUrl: "https://example.com/cooler8.jpg",
  },
  {
    id: "cooler009",
    title: "Sample CPU Cooler Model 9",
    name: "Scythe Fuma 2",
    fanRPM: "1200",
    noiseLevel: "24.9 dB",
    radiatorSize: "120mm",
    rating: 4.4,
    price: 59,
    description: "Sample description for CPU cooler model 9. Compact dual-tower cooler with excellent noise levels and good performance.",
    imageUrl: "https://example.com/cooler9.jpg",
  },
  {
    id: "cooler010",
    title: "Sample CPU Cooler Model 10",
    name: "NZXT Kraken Z63",
    fanRPM: "1800",
    noiseLevel: "27 dB",
    radiatorSize: "280mm",
    rating: 4.5,
    price: 249,
    description: "Sample description for CPU cooler model 10. Premium liquid cooler with LCD display and excellent cooling performance.",
    imageUrl: "https://example.com/cooler10.jpg",
  },
  {
    id: "cooler011",
    title: "Sample CPU Cooler Model 11",
    name: "Thermalright Peerless Assassin 120",
    fanRPM: "1550",
    noiseLevel: "25.6 dB",
    radiatorSize: "120mm",
    rating: 4.3,
    price: 45,
    description: "Sample description for CPU cooler model 11. Affordable dual-tower cooler with excellent performance and low noise.",
    imageUrl: "https://example.com/cooler11.jpg",
  },
  {
    id: "cooler012",
    title: "Sample CPU Cooler Model 12",
    name: "Corsair H115i RGB Platinum",
    fanRPM: "2000",
    noiseLevel: "26 dB",
    radiatorSize: "280mm",
    rating: 4.4,
    price: 159,
    description: "Sample description for CPU cooler model 12. High-performance 280mm liquid cooler with RGB lighting and excellent thermal performance.",
    imageUrl: "https://example.com/cooler12.jpg",
  },
  {
    id: "cooler013",
    title: "Sample CPU Cooler Model 13",
    name: "be quiet! Pure Rock 2",
    fanRPM: "1500",
    noiseLevel: "26.8 dB",
    radiatorSize: "120mm",
    rating: 4.1,
    price: 39,
    description: "Sample description for CPU cooler model 13. Compact air cooler with good performance and low noise operation.",
    imageUrl: "https://example.com/cooler13.jpg",
  },
  {
    id: "cooler014",
    title: "Sample CPU Cooler Model 14",
    name: "Arctic Freezer 34 eSports DUO",
    fanRPM: "2000",
    noiseLevel: "29 dB",
    radiatorSize: "120mm",
    rating: 4.2,
    price: 49,
    description: "Sample description for CPU cooler model 14. Gaming-focused air cooler with dual fans and good thermal performance.",
    imageUrl: "https://example.com/cooler14.jpg",
  },
  {
    id: "cooler015",
    title: "Sample CPU Cooler Model 15",
    name: "NZXT Kraken X62",
    fanRPM: "1800",
    noiseLevel: "27 dB",
    radiatorSize: "280mm",
    rating: 4.3,
    price: 149,
    description: "Sample description for CPU cooler model 15. Premium 280mm liquid cooler with excellent aesthetics and performance.",
    imageUrl: "https://example.com/cooler15.jpg",
  },
  {
    id: "cooler016",
    title: "Sample CPU Cooler Model 16",
    name: "Cooler Master MasterLiquid ML240L",
    fanRPM: "2000",
    noiseLevel: "30 dB",
    radiatorSize: "240mm",
    rating: 4.0,
    price: 79,
    description: "Sample description for CPU cooler model 16. Affordable liquid cooler with RGB lighting and good performance.",
    imageUrl: "https://example.com/cooler16.jpg",
  },
  {
    id: "cooler017",
    title: "Sample CPU Cooler Model 17",
    name: "Noctua NH-U12A",
    fanRPM: "2000",
    noiseLevel: "22.4 dB",
    radiatorSize: "120mm",
    rating: 4.5,
    price: 99,
    description: "Sample description for CPU cooler model 17. Compact air cooler with excellent noise levels and thermal performance.",
    imageUrl: "https://example.com/cooler17.jpg",
  },
  {
    id: "cooler018",
    title: "Sample CPU Cooler Model 18",
    name: "Corsair H100i Platinum SE",
    fanRPM: "2400",
    noiseLevel: "28 dB",
    radiatorSize: "240mm",
    rating: 4.4,
    price: 169,
    description: "Sample description for CPU cooler model 18. Premium white liquid cooler with RGB lighting and excellent performance.",
    imageUrl: "https://example.com/cooler18.jpg",
  },
  {
    id: "cooler019",
    title: "Sample CPU Cooler Model 19",
    name: "DeepCool GAMMAXX 400",
    fanRPM: "1500",
    noiseLevel: "32 dB",
    radiatorSize: "120mm",
    rating: 3.9,
    price: 24,
    description: "Sample description for CPU cooler model 19. Budget air cooler with decent performance for basic builds.",
    imageUrl: "https://example.com/cooler19.jpg",
  },
  {
    id: "cooler020",
    title: "Sample CPU Cooler Model 20",
    name: "be quiet! Shadow Rock 3",
    fanRPM: "1600",
    noiseLevel: "25.4 dB",
    radiatorSize: "120mm",
    rating: 4.2,
    price: 49,
    description: "Sample description for CPU cooler model 20. Silent air cooler with good performance and low noise operation.",
    imageUrl: "https://example.com/cooler20.jpg",
  },
  {
    id: "cooler021",
    title: "Sample CPU Cooler Model 21",
    name: "Arctic Liquid Freezer II 420",
    fanRPM: "2000",
    noiseLevel: "22.5 dB",
    radiatorSize: "420mm",
    rating: 4.8,
    price: 149,
    description: "Sample description for CPU cooler model 21. Massive 420mm liquid cooler with exceptional cooling performance and low noise.",
    imageUrl: "https://example.com/cooler21.jpg",
  },
  {
    id: "cooler022",
    title: "Sample CPU Cooler Model 22",
    name: "Corsair H60",
    fanRPM: "1700",
    noiseLevel: "28 dB",
    radiatorSize: "120mm",
    rating: 4.0,
    price: 79,
    description: "Sample description for CPU cooler model 22. Compact 120mm liquid cooler with good performance for small builds.",
    imageUrl: "https://example.com/cooler22.jpg",
  },
  {
    id: "cooler023",
    title: "Sample CPU Cooler Model 23",
    name: "Noctua NH-L9i",
    fanRPM: "2500",
    noiseLevel: "23.6 dB",
    radiatorSize: "95mm",
    rating: 4.3,
    price: 44,
    description: "Sample description for CPU cooler model 23. Ultra-compact air cooler perfect for mini-ITX builds and low-profile cases.",
    imageUrl: "https://example.com/cooler23.jpg",
  },
  {
    id: "cooler024",
    title: "Sample CPU Cooler Model 24",
    name: "NZXT Kraken M22",
    fanRPM: "1800",
    noiseLevel: "27 dB",
    radiatorSize: "120mm",
    rating: 4.1,
    price: 89,
    description: "Sample description for CPU cooler model 24. Compact liquid cooler with good performance for small form factor builds.",
    imageUrl: "https://example.com/cooler24.jpg",
  },
  {
    id: "cooler025",
    title: "Sample CPU Cooler Model 25",
    name: "Thermalright ARO-M14G",
    fanRPM: "1500",
    noiseLevel: "25.6 dB",
    radiatorSize: "140mm",
    rating: 4.2,
    price: 69,
    description: "Sample description for CPU cooler model 25. Single-tower air cooler with 140mm fan for good performance and low noise.",
    imageUrl: "https://example.com/cooler25.jpg",
  },
  {
    id: "cooler026",
    title: "Sample CPU Cooler Model 26",
    name: "Corsair H80i v2",
    fanRPM: "2400",
    noiseLevel: "30 dB",
    radiatorSize: "120mm",
    rating: 4.0,
    price: 99,
    description: "Sample description for CPU cooler model 26. Thick 120mm liquid cooler with dual fans for enhanced cooling performance.",
    imageUrl: "https://example.com/cooler26.jpg",
  },
  {
    id: "cooler027",
    title: "Sample CPU Cooler Model 27",
    name: "be quiet! Dark Rock TF2",
    fanRPM: "1400",
    noiseLevel: "24.3 dB",
    radiatorSize: "135mm",
    rating: 4.4,
    price: 79,
    description: "Sample description for CPU cooler model 27. Top-down air cooler with excellent noise levels and good performance.",
    imageUrl: "https://example.com/cooler27.jpg",
  },
  {
    id: "cooler028",
    title: "Sample CPU Cooler Model 28",
    name: "Arctic Freezer 50",
    fanRPM: "2000",
    noiseLevel: "29 dB",
    radiatorSize: "120mm",
    rating: 4.1,
    price: 59,
    description: "Sample description for CPU cooler model 28. Gaming-focused air cooler with RGB lighting and good thermal performance.",
    imageUrl: "https://example.com/cooler28.jpg",
  },
  {
    id: "cooler029",
    title: "Sample CPU Cooler Model 29",
    name: "Noctua NH-D15S",
    fanRPM: "1500",
    noiseLevel: "24.6 dB",
    radiatorSize: "140mm",
    rating: 4.6,
    price: 89,
    description: "Sample description for CPU cooler model 29. Single-fan version of the NH-D15 with excellent compatibility and performance.",
    imageUrl: "https://example.com/cooler29.jpg",
  },
  {
    id: "cooler030",
    title: "Sample CPU Cooler Model 30",
    name: "Corsair H170i Elite Capellix",
    fanRPM: "2400",
    noiseLevel: "28 dB",
    radiatorSize: "420mm",
    rating: 4.7,
    price: 249,
    description: "Sample description for CPU cooler model 30. Massive 420mm liquid cooler with RGB lighting and exceptional cooling performance.",
    imageUrl: "https://example.com/cooler30.jpg",
  },
];

// async function uploadCPUCoolerData() {
//   const sparePartsRef = collection(db, "SparePart");

//   for (let cooler of cpuCoolerData) {
//     try {
//       await setDoc(doc(sparePartsRef, cooler.id), cooler);
//       console.log(`✅ Uploaded: ${cooler.title}`);
//     } catch (err) {
//       console.error(`❌ Failed to upload ${cooler.title}:`, err);
//     }
//   }

//   console.log("🎉 All CPU Cooler data uploaded!");
// }

// uploadCPUCoolerData();

for (let cooler of cpuCoolerData) {
  try {
    await setDoc(doc(db, "cpuCoolerData", cooler.id), cooler);
    console.log(`✅ Uploaded: ${cooler.title}`);
  } catch (err) {
    console.error(`❌ Failed to upload ${cooler.title}:`, err);
  }
} 