import { initializeApp } from "firebase/app";
import { getFirestore, collection, setDoc, doc } from "firebase/firestore";
import { db } from "./firebase-config.js"; // Adjust the import path as necessary

const ramData = [
  {
    id: "ram001",
    title: "Sample RAM Model 1",
    name: "Corsair Vengeance LPX",
    speed: "3200MHz",
    modules: "2x8GB",
    casLatency: 16,
    firstWordLatency: "10ns",
    rating: 4.2,
    price: 89,
    description: "Sample description for RAM model 1. High-performance DDR4 memory for gaming and productivity.",
    imageUrl: "https://example.com/ram1.jpg",
  },
  {
    id: "ram002",
    title: "Sample RAM Model 2",
    name: "G.Skill Ripjaws V",
    speed: "3600MHz",
    modules: "2x16GB",
    casLatency: 18,
    firstWordLatency: "10ns",
    rating: 4.4,
    price: 129,
    description: "Sample description for RAM model 2. Fast DDR4 memory with excellent performance.",
    imageUrl: "https://example.com/ram2.jpg",
  },
  {
    id: "ram003",
    title: "Sample RAM Model 3",
    name: "Crucial Ballistix",
    speed: "4000MHz",
    modules: "2x8GB",
    casLatency: 18,
    firstWordLatency: "9ns",
    rating: 4.6,
    price: 149,
    description: "Sample description for RAM model 3. High-speed DDR4 memory for enthusiasts.",
    imageUrl: "https://example.com/ram3.jpg",
  },
  {
    id: "ram004",
    title: "Sample RAM Model 4",
    name: "Kingston Fury Beast",
    speed: "3466MHz",
    modules: "2x16GB",
    casLatency: 17,
    firstWordLatency: "9.8ns",
    rating: 4.1,
    price: 119,
    description: "Sample description for RAM model 4. Reliable DDR4 memory with good performance.",
    imageUrl: "https://example.com/ram4.jpg",
  },
  {
    id: "ram005",
    title: "Sample RAM Model 5",
    name: "Team T-Force Delta",
    speed: "3800MHz",
    modules: "2x8GB",
    casLatency: 18,
    firstWordLatency: "9.5ns",
    rating: 4.3,
    price: 139,
    description: "Sample description for RAM model 5. RGB DDR4 memory with excellent speed.",
    imageUrl: "https://example.com/ram5.jpg",
  },
  {
    id: "ram006",
    title: "Sample RAM Model 6",
    name: "Patriot Viper Steel",
    speed: "4400MHz",
    modules: "2x8GB",
    casLatency: 19,
    firstWordLatency: "8.6ns",
    rating: 4.7,
    price: 189,
    description: "Sample description for RAM model 6. Ultra-fast DDR4 memory for extreme performance.",
    imageUrl: "https://example.com/ram6.jpg",
  },
  {
    id: "ram007",
    title: "Sample RAM Model 7",
    name: "ADATA XPG Spectrix",
    speed: "3600MHz",
    modules: "2x16GB",
    casLatency: 17,
    firstWordLatency: "9.4ns",
    rating: 4.2,
    price: 159,
    description: "Sample description for RAM model 7. RGB DDR4 memory with great aesthetics.",
    imageUrl: "https://example.com/ram7.jpg",
  },
  {
    id: "ram008",
    title: "Sample RAM Model 8",
    name: "HyperX Predator",
    speed: "4000MHz",
    modules: "2x16GB",
    casLatency: 19,
    firstWordLatency: "9.5ns",
    rating: 4.5,
    price: 199,
    description: "Sample description for RAM model 8. High-performance DDR4 memory for gaming.",
    imageUrl: "https://example.com/ram8.jpg",
  },
  {
    id: "ram009",
    title: "Sample RAM Model 9",
    name: "Corsair Dominator Platinum",
    speed: "4800MHz",
    modules: "2x8GB",
    casLatency: 20,
    firstWordLatency: "8.3ns",
    rating: 4.8,
    price: 249,
    description: "Sample description for RAM model 9. Premium DDR4 memory with extreme performance.",
    imageUrl: "https://example.com/ram9.jpg",
  },
  {
    id: "ram010",
    title: "Sample RAM Model 10",
    name: "G.Skill Trident Z Royal",
    speed: "4266MHz",
    modules: "2x16GB",
    casLatency: 19,
    firstWordLatency: "8.9ns",
    rating: 4.6,
    price: 229,
    description: "Sample description for RAM model 10. Luxury DDR4 memory with premium design.",
    imageUrl: "https://example.com/ram10.jpg",
  },
  {
    id: "ram011",
    title: "Sample RAM Model 11",
    name: "Crucial Ballistix MAX",
    speed: "5100MHz",
    modules: "2x8GB",
    casLatency: 20,
    firstWordLatency: "7.8ns",
    rating: 4.9,
    price: 299,
    description: "Sample description for RAM model 11. Ultra-high-speed DDR4 memory for enthusiasts.",
    imageUrl: "https://example.com/ram11.jpg",
  },
  {
    id: "ram012",
    title: "Sample RAM Model 12",
    name: "Kingston Fury Renegade",
    speed: "4600MHz",
    modules: "2x16GB",
    casLatency: 19,
    firstWordLatency: "8.3ns",
    rating: 4.4,
    price: 259,
    description: "Sample description for RAM model 12. High-performance DDR4 memory with RGB.",
    imageUrl: "https://example.com/ram12.jpg",
  },
  {
    id: "ram013",
    title: "Sample RAM Model 13",
    name: "Team T-Force Xtreem",
    speed: "4800MHz",
    modules: "2x8GB",
    casLatency: 20,
    firstWordLatency: "8.3ns",
    rating: 4.7,
    price: 269,
    description: "Sample description for RAM model 13. Extreme DDR4 memory for overclocking.",
    imageUrl: "https://example.com/ram13.jpg",
  },
  {
    id: "ram014",
    title: "Sample RAM Model 14",
    name: "Patriot Viper RGB",
    speed: "3600MHz",
    modules: "2x32GB",
    casLatency: 18,
    firstWordLatency: "10ns",
    rating: 4.3,
    price: 189,
    description: "Sample description for RAM model 14. High-capacity DDR4 memory with RGB lighting.",
    imageUrl: "https://example.com/ram14.jpg",
  },
  {
    id: "ram015",
    title: "Sample RAM Model 15",
    name: "ADATA XPG D60G",
    speed: "4133MHz",
    modules: "2x16GB",
    casLatency: 19,
    firstWordLatency: "9.2ns",
    rating: 4.5,
    price: 219,
    description: "Sample description for RAM model 15. High-speed DDR4 memory with dual-color RGB.",
    imageUrl: "https://example.com/ram15.jpg",
  },
  {
    id: "ram016",
    title: "Sample RAM Model 16",
    name: "HyperX Fury",
    speed: "3200MHz",
    modules: "2x8GB",
    casLatency: 16,
    firstWordLatency: "10ns",
    rating: 4.0,
    price: 79,
    description: "Sample description for RAM model 16. Reliable DDR4 memory for everyday use.",
    imageUrl: "https://example.com/ram16.jpg",
  },
  {
    id: "ram017",
    title: "Sample RAM Model 17",
    name: "Corsair Vengeance RGB Pro",
    speed: "4000MHz",
    modules: "2x16GB",
    casLatency: 18,
    firstWordLatency: "9ns",
    rating: 4.4,
    price: 179,
    description: "Sample description for RAM model 17. RGB DDR4 memory with excellent performance.",
    imageUrl: "https://example.com/ram17.jpg",
  },
  {
    id: "ram018",
    title: "Sample RAM Model 18",
    name: "G.Skill Aegis",
    speed: "3000MHz",
    modules: "2x8GB",
    casLatency: 16,
    firstWordLatency: "10.7ns",
    rating: 3.8,
    price: 69,
    description: "Sample description for RAM model 18. Budget-friendly DDR4 memory.",
    imageUrl: "https://example.com/ram18.jpg",
  },
  {
    id: "ram019",
    title: "Sample RAM Model 19",
    name: "Crucial Ballistix Sport",
    speed: "3200MHz",
    modules: "2x16GB",
    casLatency: 16,
    firstWordLatency: "10ns",
    rating: 4.1,
    price: 99,
    description: "Sample description for RAM model 19. Reliable DDR4 memory for gaming.",
    imageUrl: "https://example.com/ram19.jpg",
  },
  {
    id: "ram020",
    title: "Sample RAM Model 20",
    name: "Kingston ValueRAM",
    speed: "2666MHz",
    modules: "2x8GB",
    casLatency: 19,
    firstWordLatency: "14.3ns",
    rating: 3.5,
    price: 59,
    description: "Sample description for RAM model 20. Entry-level DDR4 memory for basic systems.",
    imageUrl: "https://example.com/ram20.jpg",
  },
  {
    id: "ram021",
    title: "Sample RAM Model 21",
    name: "Team Elite Plus",
    speed: "2400MHz",
    modules: "2x4GB",
    casLatency: 17,
    firstWordLatency: "14.2ns",
    rating: 3.3,
    price: 39,
    description: "Sample description for RAM model 21. Basic DDR4 memory for entry-level builds.",
    imageUrl: "https://example.com/ram21.jpg",
  },
  {
    id: "ram022",
    title: "Sample RAM Model 22",
    name: "Patriot Signature Line",
    speed: "2666MHz",
    modules: "2x16GB",
    casLatency: 19,
    firstWordLatency: "14.3ns",
    rating: 3.7,
    price: 89,
    description: "Sample description for RAM model 22. Affordable DDR4 memory with good capacity.",
    imageUrl: "https://example.com/ram22.jpg",
  },
  {
    id: "ram023",
    title: "Sample RAM Model 23",
    name: "ADATA Premier",
    speed: "3200MHz",
    modules: "2x8GB",
    casLatency: 16,
    firstWordLatency: "10ns",
    rating: 4.0,
    price: 79,
    description: "Sample description for RAM model 23. Reliable DDR4 memory for everyday computing.",
    imageUrl: "https://example.com/ram23.jpg",
  },
  {
    id: "ram024",
    title: "Sample RAM Model 24",
    name: "HyperX Impact",
    speed: "3200MHz",
    modules: "2x16GB",
    casLatency: 20,
    firstWordLatency: "12.5ns",
    rating: 4.2,
    price: 129,
    description: "Sample description for RAM model 24. SODIMM DDR4 memory for laptops and mini-PCs.",
    imageUrl: "https://example.com/ram24.jpg",
  },
  {
    id: "ram025",
    title: "Sample RAM Model 25",
    name: "Corsair Vengeance LPX",
    speed: "3600MHz",
    modules: "2x32GB",
    casLatency: 18,
    firstWordLatency: "10ns",
    rating: 4.3,
    price: 199,
    description: "Sample description for RAM model 25. High-capacity DDR4 memory for workstations.",
    imageUrl: "https://example.com/ram25.jpg",
  },
  {
    id: "ram026",
    title: "Sample RAM Model 26",
    name: "G.Skill Ripjaws V",
    speed: "4400MHz",
    modules: "2x8GB",
    casLatency: 19,
    firstWordLatency: "8.6ns",
    rating: 4.6,
    price: 189,
    description: "Sample description for RAM model 26. High-speed DDR4 memory for enthusiasts.",
    imageUrl: "https://example.com/ram26.jpg",
  },
  {
    id: "ram027",
    title: "Sample RAM Model 27",
    name: "Crucial Ballistix",
    speed: "3800MHz",
    modules: "2x16GB",
    casLatency: 18,
    firstWordLatency: "9.5ns",
    rating: 4.4,
    price: 159,
    description: "Sample description for RAM model 27. Reliable DDR4 memory with good performance.",
    imageUrl: "https://example.com/ram27.jpg",
  },
  {
    id: "ram028",
    title: "Sample RAM Model 28",
    name: "Kingston Fury Beast",
    speed: "4000MHz",
    modules: "2x8GB",
    casLatency: 19,
    firstWordLatency: "9.5ns",
    rating: 4.5,
    price: 149,
    description: "Sample description for RAM model 28. High-performance DDR4 memory for gaming.",
    imageUrl: "https://example.com/ram28.jpg",
  },
  {
    id: "ram029",
    title: "Sample RAM Model 29",
    name: "Team T-Force Delta",
    speed: "4600MHz",
    modules: "2x16GB",
    casLatency: 19,
    firstWordLatency: "8.3ns",
    rating: 4.7,
    price: 239,
    description: "Sample description for RAM model 29. Ultra-fast DDR4 memory with RGB lighting.",
    imageUrl: "https://example.com/ram29.jpg",
  },
  {
    id: "ram030",
    title: "Sample RAM Model 30",
    name: "Patriot Viper Steel",
    speed: "5200MHz",
    modules: "2x8GB",
    casLatency: 20,
    firstWordLatency: "7.7ns",
    rating: 4.9,
    price: 319,
    description: "Sample description for RAM model 30. Extreme DDR4 memory for maximum performance.",
    imageUrl: "https://example.com/ram30.jpg",
  },
];

// async function uploadRAMData() {
//   const sparePartsRef = collection(db, "SparePart");

//   for (let ram of ramData) {
//     try {
//       await setDoc(doc(sparePartsRef, ram.id), ram);
//       console.log(`✅ Uploaded: ${ram.title}`);
//     } catch (err) {
//       console.error(`❌ Failed to upload ${ram.title}:`, err);
//     }
//   }

//   console.log("🎉 All RAM data uploaded!");
// }

// uploadRAMData();

for (let ram of ramData) {
  try {
    await setDoc(doc(db, "ramData", ram.id), ram);
    console.log(`✅ Uploaded: ${ram.title}`);
  } catch (err) {
    console.error(`❌ Failed to upload ${ram.title}:`, err);
  }
}
